# Generated by Django 5.1.1 on 2024-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
